#!/bin/bash
#fannuel wamambo, Ryan Crichton
# chkconfig: - 80 15
# description: basex server
#
# Get function from functions library
#. /etc/init.d/functions
# Start the service Basex
BASEX_HOME=/opt/basex
#
# java hme
JAVA_HOME=/opt/java/jdk1.7.0_51
export JAVA_HOME=/opt/java/jdk1.7.0_51
PATH=$JAVA_HOME/bin:$PATH
export PATH
#
start() {
echo "Starting BaseX server: "
# cd into $BASEX_HOME/bin for openinfoman implementation
cd $BASEX_HOME/bin/    
exec ./basexhttp -S
       ### Create the lock file ###
        touch /var/lock/subsys/basex


}
# Restart the service basex
stop() {
exec $BASEX_HOME/bin/basexhttpstop -S
echo "Stopping BaseX server: "
        killproc basex
        ### Now, delete the lock file ###
        rm -f /var/lock/subsys/basex

}
### main logic ###
case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  status)
        status basex
        ;;
  restart|reload|condrestart)
        
	stop  
	start
        ;;
  *)
        echo $"Usage: $0 {start|stop|restart|reload|status}"
        exit 1
esac
exit 0
